### ISSUE TITLE
Вопрос: Почему лучше множество?

### ISSUE THREAD

**Issue by distort86** [AlinaZakharova1997/Tokenizator#17]
https://github.com/AlinaZakharova1997/Tokenizator/blob/6e0c57bda3e5b03be1e66708f0fcf8319f2935ae/get_all_mod.py#L34

Ответ:
Множество лучше, потому что дальше делаются проверки с использованием оператора in, за которым в случае массива стоит полный перебор элементов массива и сравнение их с искомым, а в случае множества -- одна операция проверки наличия ключа в хеш-таблице.

А зачем Вам обращаться к элементу массива?

**Comment by AlinaZakharova1997** [comment]
Я выводила каждый элемент, чтобы убедится, что он есть.

**Comment by AlinaZakharova1997** [comment]
Я еще хотела уточнить, на каком этапе лучше собирать леммы?

**Comment by distort86** [comment]
Чтобы вывести все элементы множества, его можно проитерировать так же, как и список:

```
s = {1, 2}
for x in s:
    print(x)
```

Вопрос про леммы не понял: Вы же их уже и так собираете?

**Comment by AlinaZakharova1997** [comment]
Я их записываю вроде в файл да. У меня пока другая проблема. Программа доходит только до print('search'), url ссылка не парситься. Я хотела разобраться почему. И почему вообще такое часто бывает, когда часть кода не достигается?

**Comment by distort86** [comment]
Так бывает, когда в функции, например, происходит return до достижения этого блока кода, либо он содержится в if, который никогда не выполняется

**Comment by distort86** [comment]
Как вариант, не срабатывает цикл по xpath. Возможно, они изменили структуру html, и старый xpath больше не работает. Обратите внимание: на странице результатов поиска вверху отображается сообщение, что это новая версия интерфейса, и даётся ссылка на старую.
